CREATE TABLE TXN (
 TxnID INT PRIMARY KEY,
 AccountID INT NOT NULL,
 Amount DECIMAL(12, 2) NOT NULL CHECK(Amount > 0),
 Type ENUM('DEPOSIT','WITHDRAW') NOT NULL,
 TxnTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID)
);