ALTER TABLE Orders 
MODIFY COLUMN order_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MODIFY COLUMN customer_name VARCHAR(100) NOT NULL,
MODIFY COLUMN order_date DATE,
MODIFY COLUMN status ENUM('PENDING', 'PAID', 'SHIPPED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
MODIFY COLUMN total_amount DECIMAL(10, 2),
ADD COLUMN payment_method ENUM('CASH', 'CARD', 'TRANSFER') NOT NULL DEFAULT 'CASH';