CREATE TABLE LOAN(
 LoanID INT PRIMARY KEY,
 MemberID INT NOT NULL,
 BookID INT NOT NULL ,
 LoanDate DATE NOT NULL,
 DueDate DATE NOT NULL,
 ReturnDate DATE,
 Status ENUM('BORROWED','RETURNED','OVERDUE') DEFAULT 'BORROWED' NOT NULL,
 Fine DECIMAL(8,2) NOT NULL DEFAULT 0,
 FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID),
 FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);