CREATE TABLE SALE_TRANSACTION(
 TxnID INT PRIMARY KEY, 
 CustID INT NOT NULL,
 ProductID INT NOT NULL,
 EmpID INT NOT NULL, 
 TxnDate DATE NOT NULL, 
 Quantity INT NOT NULL,
 UnitPrice DECIMAL(10, 2) NOT NULL,
 Discount DECIMAL(5, 2) NOT NULL DEFAULT 0, 
 PaymentMethod ENUM('CASH', 'CARD', 'TRANSFER') NOT NULL,
 Notes VARCHAR(255),
 FOREIGN KEY (CustID) REFERENCES CUSTOMER(CustID),
 FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
 FOREIGN KEY (EmpID) REFERENCES EMPLOYEE(EmpID)
);