CREATE TABLE REVIEW(
 ReviewID INT NOT NULL PRIMARY KEY,
 CustID INT NOT NULL UNIQUE,
 ProductID INT NOT NULL UNIQUE,
 Comment VARCHAR(500),
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
 Rating INT NOT NULL CHECK(Rating >= 1 AND Rating <= 5),
 FOREIGN KEY (CustID) REFERENCES CUSTOMER(CustID),
 FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);