ALTER TABLE DeliveryOrders 
MODIFY COLUMN order_item_id INT PRIMARY KEY NOT NULL,
MODIFY COLUMN order_id VARCHAR(50) NOT NULL,
MODIFY COLUMN customer_phone VARCHAR(20) NOT NULL,
MODIFY COLUMN address VARCHAR(255) NOT NULL,
MODIFY COLUMN shipping_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
MODIFY COLUMN shipping_method ENUM('STANDARD', 'EXPRESS', 'SAME_DAY') DEFAULT 'STANDARD' NOT NULL,
MODIFY COLUMN cod_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
MODIFY COLUMN delivery_status ENUM('PENDING','SHIPPING', 'DELIVERED', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
MODIFY COLUMN created_text DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME,
DROP COLUMN temp_note;