ALTER TABLE Products
MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MODIFY price DECIMAL(10, 2) NOT NULL CHECK(price >= 0),
MODIFY status ENUM('ACTIVE', 'INACTIVE', 'DISCONTINUED') NOT NULL DEFAULT 'ACTIVE',
MODIFY created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
MODIFY category VARCHAR(100) NOT NULL,
DROP temp_note;
